#!/bin/bash


if pidof -o %PPID -x "airscr">/dev/null;
then
    zenity --error --text="Daemon already running. Connect device via USB if the window is not visible" --title="airscr" --width=300 --height=100

else
    dest_dir=$HOME/.local/share/airscr_ip
    adb start-server
    source $dest_dir
    adb connect $IP_ADDR
    sleep 3

    adb_check=`adb devices | awk -F " " 'FNR>1 {print $2}'`
    
    if [[ $adb_check == *"device"* ]]; 
    then
        dev_id=`adb devices | awk -F " " 'FNR==2 {print $1}' | awk -F ":" '{print $1}'`
        if [[ $dev_id =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IP_ADDR=$dev_id" > $dest_dir
            scrcpy -s $dev_id --bit-rate 2M --max-size 800 --window-x 1500 --window-y 150 --window-title "$USER's Phone"
        else
            dev_id=`adb devices | awk -F " " 'FNR==2 {print $1}'`
            ip_addr=`adb -s $dev_id shell ip addr show wlan0 | grep "inet\s" | awk '{print $2}' | awk -F'/' '{print $1}'`
            adb -s $dev_id tcpip 5555
            sleep 2
            adb connect $ip_addr
            echo "IP_ADDR=$ip_addr" > $dest_dir
            scrcpy -s $ip_addr --bit-rate 2M --max-size 800 --window-x 1500 --window-y 150 --window-title "$USER's Phone"
        fi

    else
        notify-send -t 6000 "ADB IP not found... Connect your device via USB"
        
        while true
        do
        
            if [[ `adb devices | awk -F " " 'FNR>1 {print $2}'` == *"device"* ]];
            then
                ip_addr=`adb shell ip addr show wlan0 | grep "inet\s" | awk '{print $2}' | awk -F'/' '{print $1}'`
                adb tcpip 5555
                notify-send -t 6000 "You can remove the device now" 
                sleep 3
                if [[ `hostname -I | awk -F '.' '{print $1}'` == `cut -d '.' -f1 <<<"$ip_addr"` ]] && [[ `hostname -I | awk -F '.' '{print $2}'` == `cut -d '.' -f2 <<<"$ip_addr"` ]];
                then
                    adb connect $ip_addr:5555
                    sleep 4
                    if [[ `adb devices | awk -F " " 'FNR>1 {print $2}'` == *"device"* ]];
                    then
                        echo "IP_ADDR=$ip_addr" > $dest_dir
                        scrcpy -s $ip_addr --bit-rate 2M --max-size 800 --window-x 1500 --window-y 150 --window-title "$USER's Phone"

                        break
                    fi
                else 
                    zenity --error --text="Device not on same LAN... Connect to same WiFi and try again" --title="airscr" --width=300 --height=100 
                fi
            fi
        done
    fi
fi


# cd ~/sndcpy
# ./sndcpy

